# GitHub Sponsors & Funding Links

# GitHub Sponsors
github: # Add your GitHub username if you enable GitHub Sponsors

# Other platforms (uncomment and add your usernames)
# patreon: your-patreon-username
# open_collective: your-open-collective-name
# ko_fi: your-kofi-username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: your-liberapay-username
# issuehunt: your-issuehunt-username
# otechie: your-otechie-username
# lfx_crowdfunding: project-name
# custom: ['https://your-custom-donation-link.com']
