blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/chrimar3/IoT-Transmission-Failure-Analysis-Platform/tree/main/docs
    about: Check our comprehensive documentation
  - name: Discussions
    url: https://github.com/chrimar3/IoT-Transmission-Failure-Analysis-Platform/discussions
    about: Ask questions and discuss ideas with the community
